import type { Service, Guide, Category } from './types';

export const CATEGORIES: Category[] = ['VPS Hosting', 'Web Hosting', 'VDS Servers', 'RDP Services', 'VPN Providers'];

export const SERVICES: Service[] = [
  {
    id: 1,
    name: 'DigitalOcean',
    category: 'VPS Hosting',
    description: 'Developer-friendly VPS with scalable performance.',
    logoUrl: 'https://logo.clearbit.com/digitalocean.com',
    affiliateUrl: '#',
    badges: [{ text: 'Editor’s Pick', type: 'primary' }, { text: '4.9 ★', type: 'rating' }],
    isEditorsPick: true,
    rating: 4.9,
  },
  {
    id: 2,
    name: 'Vultr',
    category: 'VPS Hosting',
    description: 'Global data centers with flexible pricing.',
    logoUrl: 'https://logo.clearbit.com/vultr.com',
    affiliateUrl: '#',
    badges: [{ text: 'Best Value', type: 'secondary' }, { text: '4.8 ★', type: 'rating' }],
    rating: 4.8,
  },
  {
    id: 3,
    name: 'Linode',
    category: 'VPS Hosting',
    description: 'Reliable VPS infrastructure with great support.',
    logoUrl: 'https://logo.clearbit.com/linode.com',
    affiliateUrl: '#',
    badges: [{ text: '4.7 ★', type: 'rating' }],
    rating: 4.7,
  },
    {
    id: 4,
    name: 'Hostinger VPS',
    category: 'VPS Hosting',
    description: 'SSD-based, beginner-friendly VPS.',
    logoUrl: 'https://logo.clearbit.com/hostinger.com',
    affiliateUrl: '#',
    badges: [{ text: '4.6 ★', type: 'rating' }],
    rating: 4.6,
  },
  {
    id: 5,
    name: 'Bluehost',
    category: 'Web Hosting',
    description: 'Reliable web hosting with 24/7 support.',
    logoUrl: 'https://logo.clearbit.com/bluehost.com',
    affiliateUrl: '#',
    badges: [{ text: '4.5 ★', type: 'rating' }],
    rating: 4.5,
  },
  {
    id: 6,
    name: 'SiteGround',
    category: 'Web Hosting',
    description: 'Managed WordPress hosting with top performance.',
    logoUrl: 'https://logo.clearbit.com/siteground.com',
    affiliateUrl: '#',
    badges: [{ text: 'Editor’s Pick', type: 'primary' }, { text: '4.9 ★', type: 'rating' }],
    isEditorsPick: true,
    rating: 4.9,
  },
  {
    id: 7,
    name: 'Gcore',
    category: 'VDS Servers',
    description: 'Powerful VDS with global content delivery.',
    logoUrl: 'https://logo.clearbit.com/gcore.com',
    affiliateUrl: '#',
    badges: [{ text: 'New', type: 'secondary' }, { text: '4.7 ★', type: 'rating' }],
    isNew: true,
    rating: 4.7,
  },
  {
    id: 8,
    name: 'VPSWALA',
    category: 'RDP Services',
    description: 'Affordable RDP services with admin access.',
    logoUrl: 'https://logo.clearbit.com/vpswala.org',
    affiliateUrl: '#',
    badges: [{ text: '4.4 ★', type: 'rating' }],
    rating: 4.4,
  },
  {
    id: 9,
    name: 'ProtonVPN',
    category: 'VPN Providers',
    description: 'High-speed Swiss VPN that safeguards your privacy.',
    logoUrl: 'https://logo.clearbit.com/protonvpn.com',
    affiliateUrl: '#',
    badges: [{ text: 'Editor’s Pick', type: 'primary' }, { text: 'Free Tier', type: 'secondary' }, { text: '4.9 ★', type: 'rating' }],
    isEditorsPick: true,
    hasFreeTier: true,
    rating: 4.9,
  },
    {
    id: 10,
    name: 'NordVPN',
    category: 'VPN Providers',
    description: 'Fast VPN for privacy and security online.',
    logoUrl: 'https://logo.clearbit.com/nordvpn.com',
    affiliateUrl: '#',
    badges: [{ text: '4.8 ★', type: 'rating' }],
    rating: 4.8,
  },
    {
    id: 11,
    name: 'Contabo',
    category: 'VPS Hosting',
    description: 'High-storage VPS at affordable prices.',
    logoUrl: 'https://logo.clearbit.com/contabo.com',
    affiliateUrl: '#',
    badges: [{ text: 'Sponsored', type: 'sponsored' }, { text: '4.3 ★', type: 'rating' }],
    isSponsored: true,
    rating: 4.3,
  },
    {
    id: 12,
    name: 'Mullvad VPN',
    category: 'VPN Providers',
    description: 'A VPN service that helps keep your online activity private.',
    logoUrl: 'https://logo.clearbit.com/mullvad.net',
    affiliateUrl: '#',
    badges: [{ text: '4.9 ★', type: 'rating' }],
    rating: 4.9,
  },
  {
    id: 13,
    name: 'Kamatera',
    category: 'VPS Hosting',
    description: 'Flexible cloud VPS for developers and businesses.',
    logoUrl: 'https://logo.clearbit.com/kamatera.com',
    affiliateUrl: '#',
    badges: [{ text: '4.7 ★', type: 'rating' }],
    rating: 4.7,
  },
  {
    id: 14,
    name: 'A2 Hosting',
    category: 'Web Hosting',
    description: 'Fast and reliable shared and VPS hosting solutions.',
    logoUrl: 'https://logo.clearbit.com/a2hosting.com',
    affiliateUrl: '#',
    badges: [{ text: 'Best Value', type: 'secondary' }, { text: '4.6 ★', type: 'rating' }],
    rating: 4.6,
  },
  {
    id: 15,
    name: 'IONOS',
    category: 'VDS Servers',
    description: 'Affordable and powerful virtual dedicated servers.',
    logoUrl: 'https://logo.clearbit.com/ionos.com',
    affiliateUrl: '#',
    badges: [{ text: '4.5 ★', type: 'rating' }],
    rating: 4.5,
  },
  {
    id: 16,
    name: 'ScalaHosting',
    category: 'VPS Hosting',
    description: 'Managed cloud VPS with SPanel control panel.',
    logoUrl: 'https://logo.clearbit.com/scalahosting.com',
    affiliateUrl: '#',
    badges: [{ text: '4.8 ★', type: 'rating' }],
    rating: 4.8,
  },
  {
    id: 17,
    name: 'Hostwinds',
    category: 'VPS Hosting',
    description: 'Customizable managed and unmanaged VPS hosting.',
    logoUrl: 'https://logo.clearbit.com/hostwinds.com',
    affiliateUrl: '#',
    badges: [{ text: '4.5 ★', type: 'rating' }],
    rating: 4.5,
  },
  {
    id: 18,
    name: 'RemoteDesktopRDP',
    category: 'RDP Services',
    description: 'Instant RDP with full admin access and SSD storage.',
    logoUrl: 'https://logo.clearbit.com/remotedesktoprdp.com',
    affiliateUrl: '#',
    badges: [{ text: '4.3 ★', type: 'rating' }],
    rating: 4.3,
  },
  {
    id: 19,
    name: 'Namecheap',
    category: 'Web Hosting',
    description: 'Affordable domain registration and web hosting.',
    logoUrl: 'https://logo.clearbit.com/namecheap.com',
    affiliateUrl: '#',
    badges: [{ text: '4.4 ★', type: 'rating' }],
    rating: 4.4,
  },
  {
    id: 20,
    name: 'Surfshark',
    category: 'VPN Providers',
    description: 'Secure your digital life with a feature-rich VPN.',
    logoUrl: 'https://logo.clearbit.com/surfshark.com',
    affiliateUrl: '#',
    badges: [{ text: 'Best Value', type: 'secondary' }, { text: '4.7 ★', type: 'rating' }],
    rating: 4.7,
  },
  {
    id: 21,
    name: 'Time4VPS',
    category: 'VDS Servers',
    description: 'Reliable and cheap VPS and VDS hosting in Europe.',
    logoUrl: 'https://logo.clearbit.com/time4vps.com',
    affiliateUrl: '#',
    badges: [{ text: '4.6 ★', type: 'rating' }],
    rating: 4.6,
  },
  {
    id: 22,
    name: 'MonoVM',
    category: 'RDP Services',
    description: 'Windows RDP VPS with flexible configurations.',
    logoUrl: 'https://logo.clearbit.com/monovm.com',
    affiliateUrl: '#',
    badges: [{ text: '4.5 ★', type: 'rating' }],
    rating: 4.5,
  },
];

export const GUIDES: Guide[] = [